
import os

html_files = [
    "G:\\要約4\\docs\\nobu_mod_the_snmod_methodref_on_viewing_normal_command.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_methodref_on_viewing_position.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_methodref_on_viewscenariodetail.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_methodref_on_viewscenariotitle.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_moddebugger.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_phogehone_singular_practice.html",
    "G:\\要約4\\docs\\nobu_mod_the_tensgmod_createpipe.html",
    "G:\\要約4\\docs\\nobu_mod_the_tr5_pluginmod.html",
    "G:\\要約4\\docs\\nobu_mod_the_tsmod_detail_exb.html",
    "G:\\要約4\\docs\\nobu_mod_the_tsmod_detail_over.html",
    "G:\\要約4\\docs\\nobu_mod_the_tsmod_detail.html",
    "G:\\要約4\\docs\\nobu_mod_the_ulua_src.html",
    "G:\\要約4\\docs\\nobu_mod_the_ulua_update.html",
    "G:\\要約4\\docs\\nobu_mod_the_wordlist_regex_compress_hm_update.html",
    "G:\\要約4\\docs\\nobu_mod_the_wordlist_regex_compress.html",
    "G:\\要約4\\docs\\nobu_site_the_profile.html",
    "G:\\要約4\\docs\\nobu_snd_inmm_ini.html",
    "G:\\要約4\\docs\\nobu_snd_inmm_principle.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_api_lv1.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_debugmonitor.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_02.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_03.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_04.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_05.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_06.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_08.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_settings_xml.html",
    "G:\\要約4\\docs\\nobu_tool_hm_autocompleteex_exam_08.html",
    "G:\\要約4\\docs\\nobu_tool_hm_autocompleteex_exam_09.html",
    "G:\\要約4\\docs\\nobu_tool_hm_autocompleteex_exam_10.html",
    "G:\\要約4\\docs\\nobu_tool_hm_autocompleteex_update.html",
    "G:\\要約4\\docs\\nobu_tool_hm_autocompleteex.html",
    "G:\\要約4\\docs\\nobu_tool_hm_baloonnotice_update.html",
    "G:\\要約4\\docs\\nobu_tool_hm_baloonnotice.html",
    "G:\\要約4\\docs\\nobu_tool_hm_baloontoast.html",
    "G:\\要約4\\docs\\nobu_tool_hm_capt_puppeteer.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt_writing_settings.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt_writing.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt35turbo_account.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt35turbo_apikey.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_methodref_on_viewing_normal_command.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_methodref_on_viewing_position.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_methodref_on_viewscenariodetail.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_methodref_on_viewscenariotitle.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_moddebugger.html",
    "G:\\要約4\\docs\\nobu_mod_the_snmod_phogehone_singular_practice.html",
    "G:\\要約4\\docs\\nobu_mod_the_tensgmod_createpipe.html",
    "G:\\要約4\\docs\\nobu_mod_the_tr5_pluginmod.html",
    "G:\\要約4\\docs\\nobu_mod_the_tsmod_detail_exb.html",
    "G:\\要約4\\docs\\nobu_mod_the_tsmod_detail_over.html",
    "G:\\要約4\\docs\\nobu_mod_the_tsmod_detail.html",
    "G:\\要約4\\docs\\nobu_mod_the_ulua_src.html",
    "G:\\要約4\\docs\\nobu_mod_the_ulua_update.html",
    "G:\\要約4\\docs\\nobu_mod_the_wordlist_regex_compress_hm_update.html",
    "G:\\要約4\\docs\\nobu_mod_the_wordlist_regex_compress.html",
    "G:\\要約4\\docs\\nobu_site_the_profile.html",
    "G:\\要約4\\docs\\nobu_snd_inmm_ini.html",
    "G:\\要約4\\docs\\nobu_snd_inmm_principle.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_api_lv1.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_debugmonitor.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_02.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_03.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_04.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_05.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_06.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_outputpane_started_08.html",
    "G:\\要約4\\docs\\nobu_tool_hm_activeperl_settings_xml.html",
    "G:\\要約4\\docs\\nobu_tool_hm_autocompleteex_exam_08.html",
    "G:\\要約4\\docs\\nobu_tool_hm_autocompleteex_exam_09.html",
    "G:\\要約4\\docs\\nobu_tool_hm_autocompleteex_exam_10.html",
    "G:\\要約4\\docs\\nobu_tool_hm_autocompleteex_update.html",
    "G:\\要約4\\docs\\nobu_tool_hm_autocompleteex.html",
    "G:\\要約4\\docs\\nobu_tool_hm_baloonnotice_update.html",
    "G:\\要約4\\docs\\nobu_tool_hm_baloonnotice.html",
    "G:\\要約4\\docs\\nobu_tool_hm_baloontoast.html",
    "G:\\要約4\\docs\\nobu_tool_hm_capt_puppeteer.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt_writing_settings.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt_writing.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt35turbo_account.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt35turbo_apikey.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt35turbo_chat_his_del.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt35turbo_settings.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt35turbo_topmost.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt35turbo_update.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt35turbo_use.html",
    "G:\\要約4\\docs\\nobu_tool_hm_chatgpt35turbo.html"
]

processed_html_files = []

for html_file_path in html_files:
    memo_file_path = html_file_path.replace(".html", ".memo")
    if not os.path.exists(memo_file_path):
        processed_html_files.append(html_file_path)

for file_path in processed_html_files:
    print(file_path)
